[project]
name = "romanesco"
version = "1.0.0"
description = "Expenses reporting system"
urls = {repository = "https://github.com/rubenseyer/romanesco"}
requires-python = ">=3.9"
readme = "README.md"
license = {file = "LICENSE"}
dependencies = [
  "Flask ~= 2.1.2",
  "apsw ~= 3.38.1",
  "pdfminer.six >= 20201018"
]
optional-dependencies = {bjoern = ["bjoern"]}

[project.scripts]
romanesco = "romanesco:__main__"

[tool.setuptools]
include-package-data = false
package-data = {romanesco = ["static/*", "templates/*", "schema.sql"]}


[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
