[project]
name = "romanesco"
version = "1.1.0"
description = "Expenses reporting system"
urls = {repository = "https://github.com/rubenseyer/romanesco"}
requires-python = ">=3.10"
readme = "README.md"
license = {file = "LICENSE"}
dependencies = [
  "Flask ~= 2.1.2",
  "apsw ~= 3.38.1",
  "pdfminer.six >= 20220506"
]

[project.optional-dependencies]
bjoern = ["bjoern"]
botccoli = [
  "selenium ~= 4.3.0",
  "requests ~= 2.28.1",
  "cryptography ~= 37.0.4"
]

[project.scripts]
romanesco = "romanesco.__main__:main"
botccoli = "romanesco.botccoli.__main__:main"

[tool.setuptools]
include-package-data = false
package-data = {romanesco = ["static/*", "templates/*", "schema.sql"]}

[tool.setuptools.packages.find]
where = [""]
include = ["romanesco*"]
namespaces = false

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
